# Generated by Django 4.0.4 on 2022-05-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=200)),
                ('Value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Year', models.CharField(max_length=200)),
                ('Rated', models.CharField(max_length=200)),
                ('Released', models.CharField(max_length=200)),
                ('Runtime', models.CharField(max_length=200)),
                ('Genre', models.CharField(max_length=200)),
                ('Director', models.CharField(max_length=200)),
                ('Writer', models.CharField(max_length=200)),
                ('Actors', models.CharField(max_length=200)),
                ('Plot', models.TextField(max_length=200)),
                ('Language', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Awards', models.CharField(max_length=200)),
                ('Poster', models.URLField(max_length=800)),
                ('Metascore', models.IntegerField()),
                ('ImdbRating', models.IntegerField()),
                ('ImdbVotes', models.IntegerField()),
                ('ImdbID', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('DVD', models.CharField(max_length=200)),
                ('BoxOffice', models.CharField(max_length=200)),
                ('Production', models.CharField(max_length=200)),
                ('Website', models.CharField(max_length=200)),
                ('Response', models.BooleanField(default=True)),
                ('Ratings', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.rating')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.comment')),
            ],
        ),
    ]
