# Generated by Django 4.0.4 on 2022-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Year', models.CharField(max_length=200)),
                ('Rated', models.CharField(max_length=200)),
                ('Released', models.CharField(max_length=200)),
                ('Runtime', models.CharField(max_length=200)),
                ('Genre', models.CharField(max_length=200)),
                ('Director', models.CharField(max_length=200)),
                ('Writer', models.CharField(max_length=200)),
                ('Actors', models.CharField(max_length=200)),
                ('Plot', models.TextField(max_length=800)),
                ('Language', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Awards', models.CharField(max_length=200)),
                ('Poster', models.CharField(default='http://', max_length=800)),
                ('Ratings', models.JSONField()),
                ('Metascore', models.CharField(max_length=200)),
                ('imdbRating', models.CharField(max_length=200)),
                ('imdbVotes', models.CharField(max_length=200)),
                ('imdbID', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('DVD', models.CharField(max_length=200)),
                ('BoxOffice', models.CharField(max_length=200)),
                ('Production', models.CharField(max_length=200)),
                ('Website', models.CharField(max_length=200)),
                ('Response', models.BooleanField(default=True)),
                ('comment', models.TextField(default='', max_length=800)),
            ],
        ),
    ]
