# Generated by Django 4.0.4 on 2022-05-12 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ImdbID',
            new_name='imdbID',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ImdbRating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ImdbVotes',
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbRating',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbVotes',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='Ratings',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
