# Generated by Django 4.0.4 on 2022-05-12 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_imdbid_movie_imdbid_remove_movie_imdbrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Metascore',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
